"""ref

Revision ID: 18fa82a22733
Revises: b6616d7c1b13
Create Date: 2024-02-16 13:18:13.361783

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '18fa82a22733'
down_revision: Union[str, None] = 'b6616d7c1b13'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'refresh_token',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'refresh_token',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
